---
title: "Transformar nuestra matriz de intensidades a un outpur procesable por `SAMseq`"
author: "Adam Casas"
date: 'Compilado: `r format(Sys.Date(), "%d de %B del %Y")`'
output: 
  html_document:
    df_print: paged
    highlight: kate
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_float: yes
---

```{r configuracion inicial, include=FALSE}
##################################################
#######        Encoded in UTF-8        ###########
##################################################

# Establecemos la configuración de los chunks
knitr::opts_chunk$set(echo = T,
                      message = F,
                      warning = F,
                      tidy = F)
set.seed(1)
```

***

# Introducción

Obtener datos en formato `.xlsx` para SAMseq (qué formato más raro):

```{r}
# cargamos el eSet normalizado del protocolo limma
eSet_normalizado <- readRDS("./matriz_intensidades/eSet_normalizado.rds")
intensidades <- as.data.frame(oligo::exprs(eSet_normalizado))

# Exploramos el dataframe de intensidades
head(intensidades)

# Ajustamos el dataframe al input esperado de SAMseq
intensidades <- cbind(rownames(intensidades), rownames(intensidades), intensidades)
colnames(intensidades) <- c("", "", 1L,2L,1L,2L,1L,2L,1L,2L) # 1 = control; 2 = genisteina
rownames(intensidades) <-  NULL

# Comprobamos que el dataframe esté listo
head(intensidades)
```

```{r, eval = F}
# Escribimos un archivo .xlsx listo para ser procesado por SAMseq
openxlsx::write.xlsx(intensidades, file = "intensidades_norm.xlsx", overwrite = T) 
```


